### ISSUE TITLE
Include xdt tool in .net 4.6.1 web app for .net core causes System.Runtime.InteropServices.RuntimeInformation error when app run

### ISSUE THREAD

**Issue by techaimail** [nil4/dotnet-transform-xdt#15] opened 2017-09-25 20:44 UTC
![image](https://user-images.githubusercontent.com/20078603/30830025-2e076cde-a208-11e7-8c4d-30810a21f35b.png)

Reference: https://github.com/aspnet/IISIntegration/issues/409#issuecomment-331620595

This tool works fine on web apps using .net core 2.0 with mvc 6 but with .net 4.6.1 with mvc 6 fails.

Thanks

**Comment by nil4** [comment] 2017-09-26 20:18
From what I can see in truncated stack trace in the screenshot, this looks like a runtime error when starting your application (as hinted by `WebHostBuilder.Build` and `WebHost.BuildApplication`). It does not look like this tool is involved from the stack trace. It would be very unusual to even have it referenced at runtime, since this is a development-time CLI tool that transforms XML files during build or publish. 

If you can publish a small, self-contained project that reproduces the error, I could try to figure out what is happening. However from the information provided so far, the problem does not seem related to the code in this repository. 

I'll close the issue for now, but please leave a comment or reopen if you can share a repro that I can investigate further. Thanks.

**Closed by nil4** 2017-09-26 20:18 UTC
